module.exports = {
  TOKEN_PAYLOAD_KEY: 'userId',
  ACCESS_TOKEN_EXPIRES_TIME: '1h',
  JWT_ACCESS_SECRET_KEY: 'JWT_ACCESS_SECRET',
  REFRESH_TOKEN_EXPIRES_TIME: '7d',
  JWT_REFRESH_SECRET_KEY: 'JWT_REFRESH_SECRET',
  BEARER: 'Bearer',
};
