name: Deploy Backend to EC2

on:
  push:
    branches: [ main ]  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/lockerit-backend .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/lockerit-backend

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PEM }}
          script: |
            docker stop lockerit-backend || true
            docker rm lockerit-backend || true
            docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/lockerit-backend || true
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/lockerit-backend
            docker run -d \
              -p 3000:3000 \
              -e NODE_ENV=production \
              -e MONGO_URI=${{ secrets.MONGO_URI }} \
              -e JWT_ACCESS_SECRET=${{ secrets.JWT_ACCESS_SECRET }} \
              -e JWT_REFRESH_SECRET=${{ secrets.JWT_REFRESH_SECRET }} \
              -e CLIENT_ORIGIN=${{ secrets.CLIENT_ORIGIN }} \
              --name lockerit-backend \
              --restart=always \
              ${{ secrets.DOCKERHUB_USERNAME }}/lockerit-backend
